-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg2NZ4EYebWVG2lVNK/dpvgYKZSeTmddD8uLFwuVeyPYmgCgYIKoZIzj0DAQehRANCAASBi8bTikWr18xPC4h01gQvlwdlvltApf7RErtDXN7siUhzU92xyZCetbKQqNQ2Z0UfbN1MGuEPMdSasov/cca8
-----END PRIVATE KEY-----